return {
  { "EdenEast/nightfox.nvim" },
  { "sainnhe/everforest" },
  { "catppuccin/nvim" },
  { "rebelot/kanagawa.nvim" },
  { "rose-pine/neovim" },
  { "luisiacc/gruvbox-baby" },
  { "savq/melange-nvim" },
  { "marko-cerovac/material.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "NLKNguyen/papercolor-theme" },
  { "cryptomilk/nightcity.nvim" },
  { "kvrohit/mellow.nvim" },
  { "AlexvZyl/nordic.nvim" },
  { "Mofiqul/dracula.nvim" },
  { "projekt0n/github-nvim-theme" },
  { "frenzyexists/aquarium-vim" },
  { "ajmwagar/vim-deus" },
  { "ribru17/bamboo.nvim" },
  { "zootedb0t/citruszest.nvim" },
  { "miikanissi/modus-themes.nvim" },
  { "nanotech/jellybeans.vim" },
  { "oxfist/night-owl.nvim" },
  { "pineapplegiant/spaceduck" },
  { "flrnd/plastic.vim" },
  { "crispybaccoon/aurora" },
}
