return {
  { "EdenEast/nightfox.nvim" },
  { "sainnhe/everforest" },
  { "catppuccin/nvim" },
  { "rebelot/kanagawa.nvim" },
  { "rose-pine/neovim" },
  { "luisiacc/gruvbox-baby" },
  { "savq/melange-nvim" },
  { "marko-cerovac/material.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "NLKNguyen/papercolor-theme" },
  { "AlexvZyl/nordic.nvim" },
  { "Mofiqul/dracula.nvim" },
  { "projekt0n/github-nvim-theme" },
  { "frenzyexists/aquarium-vim" },
  { "kvrohit/mellow.nvim" },
  { "cryptomilk/nightcity.nvim" },
}
